---
- name: Using the copy module
  hosts: all
  remote_user: root
  tasks:
    - name: Copy a file to managed hosts and set attributes
      copy:
      src: files/users.txt
      dest: /home/emran/users.txt
      owner: emran
      group: emran
      mode: u+rw,g-wx,o-rwx
      setype: samba_share_t