---
- name: Install and configure webserver with basic auth
  hosts: client2
  become_method: sudo
  become: yes
  become_user: root
  vars:
   firewall_pkg: firewalld
   web_pkg: httpd
   web_svc: httpd
   ssl_pkg: mod_ssl
   python_pkg: python-passlib
   httpdconf_src: files/httpd.conf
   httpdconf_file: /etc/httpd/conf/httpd.conf
   htaccess_src: files/.htaccess
   secrets_dir: /etc/httpd/secrets
   secrets_file: "{{ secrets_dir }}/htpasswd"
   web_root: /var/www/html
   web_user: guest
  vars_files:
   - vars/secret.yml
  tasks:
   - name: Latest version of necessary packages installed
     yum:
      name:
       - "{{ firewall_pkg }}"
       - "{{ web_pkg }}"
       - "{{ ssl_pkg }}"
       - "{{ python_pkg }}"
      state: latest
   - name: Configure web service
     copy:
      src: "{{ httpdconf_src }}"
      dest: "{{ httpdconf_file }}"
      owner: root
      group: root
      mode: 0644