---
  - name: Install the firewall
    yum:
      name: "{{ firewall_pkg }}"
      state: latest
  - name: Start the firewall
    service:
      name: "{{ firewall_svc }}"
      enabled: true
      state: starte
  - name: Open the port for {{ rule }}
    firewalld:
      service: "{{ rule }}"
      immediate: true
      permanent: true
      state: enabled